# http://localhost:7116/swagger/index.html

services:
  volto_sales:
    build: .
    container_name: volto_sales_cont
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - "7115:7115"  # big_data
      - "7116:7116"  # gateway
      - "7668:80" # front end